import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <video loop autoPlay playsInline muted>
                    <source
                        type="video/mp4"
                        src="https://elgdesign.co.uk/wp-content/uploads/2023/05/Background.mp4"
                    />
                </video>
                {children}
                <Footer />
            </body>
        </html>
    );
}
